"""Tool for saving an approved prompt after preview."""

import logging
from typing import Optional

from mcp.types import Tool, TextContent

from prompt_saver_mcp.database.mongodb_client import mongodb_client
from prompt_saver_mcp.database.models import PromptCreate
from prompt_saver_mcp.embeddings.voyage_client import voyage_client

logger = logging.getLogger(__name__)


def get_save_approved_prompt_tool() -> Tool:
    """Get the save_approved_prompt tool definition."""
    return Tool(
        name="save_approved_prompt",
        description="Save a previously previewed prompt to the database. Use this after reviewing a prompt preview generated by preview_prompt.",
        inputSchema={
            "type": "object",
            "properties": {
                "use_case": {
                    "type": "string",
                    "description": "The use case category from the preview",
                },
                "summary": {
                    "type": "string",
                    "description": "The summary from the preview",
                },
                "prompt_template": {
                    "type": "string",
                    "description": "The prompt template from the preview",
                },
                "history": {
                    "type": "string",
                    "description": "The history from the preview",
                },
                "context_info": {
                    "type": "string",
                    "description": "Additional context about the conversation (branch, PR, etc.)",
                },
            },
            "required": ["use_case", "summary", "prompt_template", "history"],
        },
    )


async def handle_save_approved_prompt(
    use_case: str,
    summary: str,
    prompt_template: str,
    history: str,
    context_info: Optional[str] = None,
) -> list[TextContent]:
    """
    Handle save_approved_prompt tool execution.

    Args:
        use_case: The use case category
        summary: The summary text
        prompt_template: The prompt template
        history: The history text
        context_info: Optional context information

    Returns:
        List of text content with result message
    """
    try:
        # Generate embedding
        logger.info("Generating embedding for approved prompt...")
        embedding = voyage_client.generate_embedding(summary)

        # Create prompt data
        prompt_data = PromptCreate(
            use_case=use_case,
            summary=summary,
            prompt_template=prompt_template,
            history=history,
            embedding=embedding,
            created_by=None,
        )

        # Save to MongoDB
        logger.info("Saving approved prompt to database...")
        prompt_id = mongodb_client.create_prompt(prompt_data)

        result_message = f"""✅ Successfully saved prompt!

**Prompt ID:** {prompt_id}
**Use Case:** {use_case}
**Summary:** {summary}

The prompt has been saved and can be retrieved using the prompt ID or searched using semantic search."""
        if context_info:
            result_message += f"\n\n**Context:** {context_info}"

        return [TextContent(type="text", text=result_message)]
    except Exception as e:
        error_message = f"Failed to save approved prompt: {str(e)}"
        logger.error(error_message, exc_info=True)
        return [TextContent(type="text", text=f"Error: {error_message}")]

